/*
 * generated by Xtext 2.9.2
 */
package uam.eagledata.dsl.events.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import uam.eagledata.dsl.events.ide.contentassist.antlr.internal.InternalEventSetManagerDslParser;
import uam.eagledata.dsl.events.services.EventSetManagerDslGrammarAccess;

public class EventSetManagerDslParser extends AbstractContentAssistParser {

	@Inject
	private EventSetManagerDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalEventSetManagerDslParser createParser() {
		InternalEventSetManagerDslParser result = new InternalEventSetManagerDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGeographicalElementAccess().getAlternatives(), "rule__GeographicalElement__Alternatives");
					put(grammarAccess.getConceptAccess().getAlternatives(), "rule__Concept__Alternatives");
					put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
					put(grammarAccess.getActionParamAccess().getAlternatives(), "rule__ActionParam__Alternatives");
					put(grammarAccess.getMethodAccess().getAlternatives(), "rule__Method__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getEventSetManagerAccess().getGroup(), "rule__EventSetManager__Group__0");
					put(grammarAccess.getEventSetManagerAccess().getGroup_0(), "rule__EventSetManager__Group_0__0");
					put(grammarAccess.getEventSetManagerAccess().getGroup_0_2(), "rule__EventSetManager__Group_0_2__0");
					put(grammarAccess.getEventSetManagerAccess().getGroup_1(), "rule__EventSetManager__Group_1__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getPointAccess().getGroup(), "rule__Point__Group__0");
					put(grammarAccess.getRegionAccess().getGroup(), "rule__Region__Group__0");
					put(grammarAccess.getRegionAccess().getGroup_4(), "rule__Region__Group_4__0");
					put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
					put(grammarAccess.getEventAccess().getGroup_1(), "rule__Event__Group_1__0");
					put(grammarAccess.getEventAccess().getGroup_1_2(), "rule__Event__Group_1_2__0");
					put(grammarAccess.getEventAccess().getGroup_8(), "rule__Event__Group_8__0");
					put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
					put(grammarAccess.getConditionAccess().getGroup_1(), "rule__Condition__Group_1__0");
					put(grammarAccess.getConditionAccess().getGroup_2(), "rule__Condition__Group_2__0");
					put(grammarAccess.getConditionAccess().getGroup_3(), "rule__Condition__Group_3__0");
					put(grammarAccess.getConditionAccess().getGroup_3_2(), "rule__Condition__Group_3_2__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getLiteralAccess().getGroup(), "rule__Literal__Group__0");
					put(grammarAccess.getKeyConceptAccess().getGroup(), "rule__KeyConcept__Group__0");
					put(grammarAccess.getRegexConceptAccess().getGroup(), "rule__RegexConcept__Group__0");
					put(grammarAccess.getConceptParamAccess().getGroup(), "rule__ConceptParam__Group__0");
					put(grammarAccess.getStringParamAccess().getGroup(), "rule__StringParam__Group__0");
					put(grammarAccess.getActionCallAccess().getGroup(), "rule__ActionCall__Group__0");
					put(grammarAccess.getActionCallAccess().getGroup_2(), "rule__ActionCall__Group_2__0");
					put(grammarAccess.getActionCallAccess().getGroup_2_2(), "rule__ActionCall__Group_2_2__0");
					put(grammarAccess.getQueryCallAccess().getGroup(), "rule__QueryCall__Group__0");
					put(grammarAccess.getQueryCallAccess().getGroup_4(), "rule__QueryCall__Group_4__0");
					put(grammarAccess.getQueryCallAccess().getGroup_10(), "rule__QueryCall__Group_10__0");
					put(grammarAccess.getQueryCallAccess().getGroup_10_2(), "rule__QueryCall__Group_10_2__0");
					put(grammarAccess.getParamValueAccess().getGroup(), "rule__ParamValue__Group__0");
					put(grammarAccess.getFirstAccess().getGroup(), "rule__First__Group__0");
					put(grammarAccess.getLastAccess().getGroup(), "rule__Last__Group__0");
					put(grammarAccess.getEventSetManagerAccess().getImportedNamespaceAssignment_0_1(), "rule__EventSetManager__ImportedNamespaceAssignment_0_1");
					put(grammarAccess.getEventSetManagerAccess().getImportedNamespaceAssignment_0_2_1(), "rule__EventSetManager__ImportedNamespaceAssignment_0_2_1");
					put(grammarAccess.getEventSetManagerAccess().getGeosAssignment_1_0(), "rule__EventSetManager__GeosAssignment_1_0");
					put(grammarAccess.getEventSetManagerAccess().getGeosAssignment_1_1(), "rule__EventSetManager__GeosAssignment_1_1");
					put(grammarAccess.getEventSetManagerAccess().getEventsAssignment_2(), "rule__EventSetManager__EventsAssignment_2");
					put(grammarAccess.getEventSetManagerAccess().getEventsAssignment_3(), "rule__EventSetManager__EventsAssignment_3");
					put(grammarAccess.getPointAccess().getNameAssignment_1(), "rule__Point__NameAssignment_1");
					put(grammarAccess.getPointAccess().getLatAssignment_3(), "rule__Point__LatAssignment_3");
					put(grammarAccess.getPointAccess().getLongAssignment_5(), "rule__Point__LongAssignment_5");
					put(grammarAccess.getRegionAccess().getNameAssignment_1(), "rule__Region__NameAssignment_1");
					put(grammarAccess.getRegionAccess().getPointsAssignment_3(), "rule__Region__PointsAssignment_3");
					put(grammarAccess.getRegionAccess().getPointsAssignment_4_1(), "rule__Region__PointsAssignment_4_1");
					put(grammarAccess.getEventAccess().getDataconnectionsAssignment_1_1(), "rule__Event__DataconnectionsAssignment_1_1");
					put(grammarAccess.getEventAccess().getDataconnectionsAssignment_1_2_1(), "rule__Event__DataconnectionsAssignment_1_2_1");
					put(grammarAccess.getEventAccess().getNameAssignment_3(), "rule__Event__NameAssignment_3");
					put(grammarAccess.getEventAccess().getConceptsAssignment_5(), "rule__Event__ConceptsAssignment_5");
					put(grammarAccess.getEventAccess().getConceptsAssignment_6(), "rule__Event__ConceptsAssignment_6");
					put(grammarAccess.getEventAccess().getWhenAssignment_8_0(), "rule__Event__WhenAssignment_8_0");
					put(grammarAccess.getEventAccess().getWhenAssignment_8_1(), "rule__Event__WhenAssignment_8_1");
					put(grammarAccess.getConditionAccess().getExpressionAssignment_1_1(), "rule__Condition__ExpressionAssignment_1_1");
					put(grammarAccess.getConditionAccess().getGeoAssignment_2_1(), "rule__Condition__GeoAssignment_2_1");
					put(grammarAccess.getConditionAccess().getTriggersAssignment_3_1(), "rule__Condition__TriggersAssignment_3_1");
					put(grammarAccess.getConditionAccess().getTriggersAssignment_3_2_1(), "rule__Condition__TriggersAssignment_3_2_1");
					put(grammarAccess.getExpressionAccess().getLeftAssignment_1(), "rule__Expression__LeftAssignment_1");
					put(grammarAccess.getExpressionAccess().getRightAssignment_3(), "rule__Expression__RightAssignment_3");
					put(grammarAccess.getLiteralAccess().getValueAssignment_1(), "rule__Literal__ValueAssignment_1");
					put(grammarAccess.getKeyConceptAccess().getTypeAssignment_1(), "rule__KeyConcept__TypeAssignment_1");
					put(grammarAccess.getKeyConceptAccess().getNameAssignment_2(), "rule__KeyConcept__NameAssignment_2");
					put(grammarAccess.getRegexConceptAccess().getTypeAssignment_1(), "rule__RegexConcept__TypeAssignment_1");
					put(grammarAccess.getRegexConceptAccess().getNameAssignment_2(), "rule__RegexConcept__NameAssignment_2");
					put(grammarAccess.getRegexConceptAccess().getRegexAssignment_4(), "rule__RegexConcept__RegexAssignment_4");
					put(grammarAccess.getConceptParamAccess().getKeyAssignment_1(), "rule__ConceptParam__KeyAssignment_1");
					put(grammarAccess.getConceptParamAccess().getValueAssignment_3(), "rule__ConceptParam__ValueAssignment_3");
					put(grammarAccess.getStringParamAccess().getKeyAssignment_1(), "rule__StringParam__KeyAssignment_1");
					put(grammarAccess.getStringParamAccess().getValueAssignment_3(), "rule__StringParam__ValueAssignment_3");
					put(grammarAccess.getActionCallAccess().getCallsAssignment_1(), "rule__ActionCall__CallsAssignment_1");
					put(grammarAccess.getActionCallAccess().getActionParamsAssignment_2_1(), "rule__ActionCall__ActionParamsAssignment_2_1");
					put(grammarAccess.getActionCallAccess().getActionParamsAssignment_2_2_1(), "rule__ActionCall__ActionParamsAssignment_2_2_1");
					put(grammarAccess.getQueryCallAccess().getSelectAssignment_1(), "rule__QueryCall__SelectAssignment_1");
					put(grammarAccess.getQueryCallAccess().getQueryParamsAssignment_3(), "rule__QueryCall__QueryParamsAssignment_3");
					put(grammarAccess.getQueryCallAccess().getQueryParamsAssignment_4_1(), "rule__QueryCall__QueryParamsAssignment_4_1");
					put(grammarAccess.getQueryCallAccess().getMethodAssignment_7(), "rule__QueryCall__MethodAssignment_7");
					put(grammarAccess.getQueryCallAccess().getCallsAssignment_9(), "rule__QueryCall__CallsAssignment_9");
					put(grammarAccess.getQueryCallAccess().getActionParamsAssignment_10_1(), "rule__QueryCall__ActionParamsAssignment_10_1");
					put(grammarAccess.getQueryCallAccess().getActionParamsAssignment_10_2_1(), "rule__QueryCall__ActionParamsAssignment_10_2_1");
					put(grammarAccess.getParamValueAccess().getParamAssignment_1(), "rule__ParamValue__ParamAssignment_1");
					put(grammarAccess.getParamValueAccess().getValueAssignment_3(), "rule__ParamValue__ValueAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalEventSetManagerDslParser typedParser = (InternalEventSetManagerDslParser) parser;
			typedParser.entryRuleEventSetManager();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public EventSetManagerDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EventSetManagerDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
