/**
 * generated by Xtext 2.9.1
 */
package eagledata.core.dsl.rule.validation;

import eagledata.core.dsl.pattern.streamingDsl.Phrase;
import eagledata.core.dsl.rule.ruleDsl.Rule;
import eagledata.core.dsl.rule.validation.AbstractRuleDslValidator;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RuleDslValidator extends AbstractRuleDslValidator {
  public final static String CONCEPTS_NAME = "conceptsInvalid";
  
  @Check
  public void checkDataTypeOptions(final Rule rule) {
    final Phrase phrase = rule.getEvent();
  }
}
