package ecarules.impl;

import ecarules.ExtendedActionExecutableExtension;

public class ExtendedActionExecutableExtensionImpl extends ActionExecutableExtensionImpl implements ExtendedActionExecutableExtension {
}
