/*
 * generated by Xtext 2.9.2
 */
package eagledata.core.dsl.ruledetection.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRuleDetectionDslScopeProvider extends DelegatingScopeProvider {
}
