/**
 * generated by Xtext 2.9.2
 */
package eagledata.core.dsl.pattern.streamingDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Language Option</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eagledata.core.dsl.pattern.streamingDsl.LanguageOption#getKey <em>Key</em>}</li>
 *   <li>{@link eagledata.core.dsl.pattern.streamingDsl.LanguageOption#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see eagledata.core.dsl.pattern.streamingDsl.StreamingDslPackage#getLanguageOption()
 * @model
 * @generated
 */
public interface LanguageOption extends Option
{
  /**
   * Returns the value of the '<em><b>Key</b></em>' attribute.
   * The literals are from the enumeration {@link eagledata.core.dsl.pattern.streamingDsl.LanguageOptionKey}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Key</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' attribute.
   * @see eagledata.core.dsl.pattern.streamingDsl.LanguageOptionKey
   * @see #setKey(LanguageOptionKey)
   * @see eagledata.core.dsl.pattern.streamingDsl.StreamingDslPackage#getLanguageOption_Key()
   * @model
   * @generated
   */
  LanguageOptionKey getKey();

  /**
   * Sets the value of the '{@link eagledata.core.dsl.pattern.streamingDsl.LanguageOption#getKey <em>Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' attribute.
   * @see eagledata.core.dsl.pattern.streamingDsl.LanguageOptionKey
   * @see #getKey()
   * @generated
   */
  void setKey(LanguageOptionKey value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * The literals are from the enumeration {@link eagledata.core.dsl.pattern.streamingDsl.Language}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see eagledata.core.dsl.pattern.streamingDsl.Language
   * @see #setValue(Language)
   * @see eagledata.core.dsl.pattern.streamingDsl.StreamingDslPackage#getLanguageOption_Value()
   * @model
   * @generated
   */
  Language getValue();

  /**
   * Sets the value of the '{@link eagledata.core.dsl.pattern.streamingDsl.LanguageOption#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see eagledata.core.dsl.pattern.streamingDsl.Language
   * @see #getValue()
   * @generated
   */
  void setValue(Language value);

} // LanguageOption
