/*
 * generated by Xtext 2.9.1
 */
package eagledata.core.dsl.datadescription.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DataDescriptionDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("eagledata/core/dsl/datadescription/parser/antlr/internal/InternalDataDescriptionDsl.tokens");
	}
}
