/*
 * generated by Xtext 2.9.2
 */
package uam.eagledata.dsl.events


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EventSetManagerDslStandaloneSetup extends EventSetManagerDslStandaloneSetupGenerated {

	def static void doSetup() {
		new EventSetManagerDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
