/*
 * generated by Xtext 2.9.2
 */
package eagledata.core.dsl.pattern


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PatternDslStandaloneSetup extends PatternDslStandaloneSetupGenerated {

	def static void doSetup() {
		new PatternDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
