/**
 * generated by Xtext 2.9.2
 */
package eagledata.core.dsl.pattern.streamingDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eagledata.core.dsl.pattern.streamingDsl.Phrase#getConnection <em>Connection</em>}</li>
 *   <li>{@link eagledata.core.dsl.pattern.streamingDsl.Phrase#getInAGeo <em>In AGeo</em>}</li>
 *   <li>{@link eagledata.core.dsl.pattern.streamingDsl.Phrase#isOrdered <em>Ordered</em>}</li>
 *   <li>{@link eagledata.core.dsl.pattern.streamingDsl.Phrase#getFeatures <em>Features</em>}</li>
 *   <li>{@link eagledata.core.dsl.pattern.streamingDsl.Phrase#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @see eagledata.core.dsl.pattern.streamingDsl.StreamingDslPackage#getPhrase()
 * @model
 * @generated
 */
public interface Phrase extends StremingDescription
{
  /**
   * Returns the value of the '<em><b>Connection</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Connection</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connection</em>' attribute.
   * @see #setConnection(String)
   * @see eagledata.core.dsl.pattern.streamingDsl.StreamingDslPackage#getPhrase_Connection()
   * @model
   * @generated
   */
  String getConnection();

  /**
   * Sets the value of the '{@link eagledata.core.dsl.pattern.streamingDsl.Phrase#getConnection <em>Connection</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Connection</em>' attribute.
   * @see #getConnection()
   * @generated
   */
  void setConnection(String value);

  /**
   * Returns the value of the '<em><b>In AGeo</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>In AGeo</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>In AGeo</em>' reference.
   * @see #setInAGeo(GeographicalElement)
   * @see eagledata.core.dsl.pattern.streamingDsl.StreamingDslPackage#getPhrase_InAGeo()
   * @model
   * @generated
   */
  GeographicalElement getInAGeo();

  /**
   * Sets the value of the '{@link eagledata.core.dsl.pattern.streamingDsl.Phrase#getInAGeo <em>In AGeo</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In AGeo</em>' reference.
   * @see #getInAGeo()
   * @generated
   */
  void setInAGeo(GeographicalElement value);

  /**
   * Returns the value of the '<em><b>Ordered</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ordered</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ordered</em>' attribute.
   * @see #setOrdered(boolean)
   * @see eagledata.core.dsl.pattern.streamingDsl.StreamingDslPackage#getPhrase_Ordered()
   * @model
   * @generated
   */
  boolean isOrdered();

  /**
   * Sets the value of the '{@link eagledata.core.dsl.pattern.streamingDsl.Phrase#isOrdered <em>Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ordered</em>' attribute.
   * @see #isOrdered()
   * @generated
   */
  void setOrdered(boolean value);

  /**
   * Returns the value of the '<em><b>Features</b></em>' containment reference list.
   * The list contents are of type {@link eagledata.core.dsl.pattern.streamingDsl.Feature}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Features</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' containment reference list.
   * @see eagledata.core.dsl.pattern.streamingDsl.StreamingDslPackage#getPhrase_Features()
   * @model containment="true"
   * @generated
   */
  EList<Feature> getFeatures();

  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference list.
   * The list contents are of type {@link eagledata.core.dsl.pattern.streamingDsl.Option}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Options</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference list.
   * @see eagledata.core.dsl.pattern.streamingDsl.StreamingDslPackage#getPhrase_Options()
   * @model containment="true"
   * @generated
   */
  EList<Option> getOptions();

} // Phrase
