/**
 * generated by Xtext 2.9.2
 */
package eagledata.core.dsl.pattern.streamingDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.xtype.XImportSection;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Streaming Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eagledata.core.dsl.pattern.streamingDsl.StreamingModel#getImportSection <em>Import Section</em>}</li>
 *   <li>{@link eagledata.core.dsl.pattern.streamingDsl.StreamingModel#getDescriptions <em>Descriptions</em>}</li>
 * </ul>
 *
 * @see eagledata.core.dsl.pattern.streamingDsl.StreamingDslPackage#getStreamingModel()
 * @model
 * @generated
 */
public interface StreamingModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Import Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Import Section</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Import Section</em>' containment reference.
   * @see #setImportSection(XImportSection)
   * @see eagledata.core.dsl.pattern.streamingDsl.StreamingDslPackage#getStreamingModel_ImportSection()
   * @model containment="true"
   * @generated
   */
  XImportSection getImportSection();

  /**
   * Sets the value of the '{@link eagledata.core.dsl.pattern.streamingDsl.StreamingModel#getImportSection <em>Import Section</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Import Section</em>' containment reference.
   * @see #getImportSection()
   * @generated
   */
  void setImportSection(XImportSection value);

  /**
   * Returns the value of the '<em><b>Descriptions</b></em>' containment reference list.
   * The list contents are of type {@link eagledata.core.dsl.pattern.streamingDsl.StremingDescription}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Descriptions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descriptions</em>' containment reference list.
   * @see eagledata.core.dsl.pattern.streamingDsl.StreamingDslPackage#getStreamingModel_Descriptions()
   * @model containment="true"
   * @generated
   */
  EList<StremingDescription> getDescriptions();

} // StreamingModel
