/**
 * generated by Xtext 2.9.2
 */
package uam.eagledata.dsl.events.validation;

import uam.eagledata.dsl.events.validation.AbstractEventSetManagerDslValidator;

@SuppressWarnings("all")
public class EventSetManagerDslValidator extends AbstractEventSetManagerDslValidator {
}
