/**
 * generated by Xtext 2.9.2
 */
package uam.eagledata.dsl.semanticnodes;

import uam.eagledata.dsl.semanticnodes.SemanticNodesDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SemanticNodesDslStandaloneSetup extends SemanticNodesDslStandaloneSetupGenerated {
  public static void doSetup() {
    SemanticNodesDslStandaloneSetup _semanticNodesDslStandaloneSetup = new SemanticNodesDslStandaloneSetup();
    _semanticNodesDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
