/**
 * generated by Xtext 2.9.2
 */
package uam.eagledata.dsl.query.ui.contentassist;

import uam.eagledata.dsl.query.ui.contentassist.AbstractQueryDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class QueryDslProposalProvider extends AbstractQueryDslProposalProvider {
}
