<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="resourceset" nsURI="http://www.core.eagledata/resourceset/DataResourceSet"
    nsPrefix="resources">
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageParts" upperBound="-1"
        eType="#//MessagePart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableColumn" eSuperTypes="#//Column">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataResourceSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//DataResource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasedOnStreamingDataResource" eSuperTypes="#//DataResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="ecore:EClass ../../eagledata.core.dsl.streamingdata/model/generated/PatternDsl.ecore#//Phrase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//MessageSet"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasedOnDescriptionDataResource" eSuperTypes="#//DataResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="ecore:EClass ../../eagledata.core.dsl.datadesc/model/generated/DataDsl.ecore#//DataDescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//Table"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataResource" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assistant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveColumn" eSuperTypes="#//Column">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metadata" eType="ecore:EClass ../../eagledata.core.dsl.datadesc/model/generated/DataDsl.ecore#//PrimitiveNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessagePart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textPart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concept" eType="ecore:EClass ../../eagledata.core.dsl.streamingdata/model/generated/PatternDsl.ecore#//Feature"/>
  </eClassifiers>
</ecore:EPackage>
