/*
 * generated by Xtext 2.9.2
 */
package uam.eagledata.dsl.annotations.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAnnotationsDslScopeProvider extends DelegatingScopeProvider {
}
