/**
 * generated by Xtext 2.9.2
 */
package eagledata.core.dsl.ruledetection.ruleDetectionDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Recipient</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.RuleDetectionDslPackage#getRecipient()
 * @model
 * @generated
 */
public interface Recipient extends EObject
{
} // Recipient
