/**
 * generated by Xtext 2.9.2
 */
package eagledata.core.dsl.ruledetection.ruleDetectionDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.RuleDetectionDslFactory
 * @model kind="package"
 * @generated
 */
public interface RuleDetectionDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ruleDetectionDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.core.eagledata/dsl/ruledetection/RuleDetectionDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ruleDetectionDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RuleDetectionDslPackage eINSTANCE = eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl.init();

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleModelImpl <em>Rule Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleModelImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getRuleModel()
   * @generated
   */
  int RULE_MODEL = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_MODEL__IMPORTS = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_MODEL__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Rule Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleElementImpl <em>Rule Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleElementImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getRuleElement()
   * @generated
   */
  int RULE_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Rule Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getRule()
   * @generated
   */
  int RULE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__EVENT = 1;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ACTIONS = 2;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ActionImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getAction()
   * @generated
   */
  int ACTION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAME = RULE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = RULE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.QueryImpl <em>Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.QueryImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getQuery()
   * @generated
   */
  int QUERY = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Select</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__SELECT = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Where</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__WHERE = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.SelectImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 6;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.AddingSelectImpl <em>Adding Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.AddingSelectImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getAddingSelect()
   * @generated
   */
  int ADDING_SELECT = 5;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDING_SELECT__OPERATION = SELECT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDING_SELECT__ELEMENT = SELECT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>All</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDING_SELECT__ALL = SELECT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Adding Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDING_SELECT_FEATURE_COUNT = SELECT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.SetSelectImpl <em>Set Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.SetSelectImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getSetSelect()
   * @generated
   */
  int SET_SELECT = 7;

  /**
   * The feature id for the '<em><b>Selection</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_SELECT__SELECTION = SELECT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_SELECT__OPERATOR = SELECT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Select</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_SELECT__SELECT = SELECT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Set Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_SELECT_FEATURE_COUNT = SELECT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.WhereImpl <em>Where</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.WhereImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getWhere()
   * @generated
   */
  int WHERE = 8;

  /**
   * The feature id for the '<em><b>Left</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE__LEFT = 0;

  /**
   * The feature id for the '<em><b>Logical Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE__LOGICAL_OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Right Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE__RIGHT_VARIABLE = 2;

  /**
   * The feature id for the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE__RIGHT = 3;

  /**
   * The number of structural features of the '<em>Where</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RecipientImpl <em>Recipient</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RecipientImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getRecipient()
   * @generated
   */
  int RECIPIENT = 9;

  /**
   * The number of structural features of the '<em>Recipient</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPIENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ConcreteRecipientImpl <em>Concrete Recipient</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ConcreteRecipientImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getConcreteRecipient()
   * @generated
   */
  int CONCRETE_RECIPIENT = 10;

  /**
   * The feature id for the '<em><b>User</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCRETE_RECIPIENT__USER = RECIPIENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Concrete Recipient</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCRETE_RECIPIENT_FEATURE_COUNT = RECIPIENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.WhenImpl <em>When</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.WhenImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getWhen()
   * @generated
   */
  int WHEN = 11;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__LEFT = 0;

  /**
   * The feature id for the '<em><b>Logical Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__LOGICAL_OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN__RIGHT = 2;

  /**
   * The number of structural features of the '<em>When</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ExpressionImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 12;

  /**
   * The feature id for the '<em><b>Plain Operand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__PLAIN_OPERAND = 0;

  /**
   * The feature id for the '<em><b>Complex Operands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__COMPLEX_OPERANDS = 1;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.OperandImpl <em>Operand</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.OperandImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getOperand()
   * @generated
   */
  int OPERAND = 13;

  /**
   * The number of structural features of the '<em>Operand</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.PlainOperandImpl <em>Plain Operand</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.PlainOperandImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getPlainOperand()
   * @generated
   */
  int PLAIN_OPERAND = 14;

  /**
   * The number of structural features of the '<em>Plain Operand</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAIN_OPERAND_FEATURE_COUNT = OPERAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.NumeralImpl <em>Numeral</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.NumeralImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getNumeral()
   * @generated
   */
  int NUMERAL = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMERAL__VALUE = PLAIN_OPERAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Numeral</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMERAL_FEATURE_COUNT = PLAIN_OPERAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.QueryOperandImpl <em>Query Operand</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.QueryOperandImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getQueryOperand()
   * @generated
   */
  int QUERY_OPERAND = 16;

  /**
   * The feature id for the '<em><b>Query</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_OPERAND__QUERY = PLAIN_OPERAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Query Operand</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_OPERAND_FEATURE_COUNT = PLAIN_OPERAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ComplexOperandImpl <em>Complex Operand</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ComplexOperandImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getComplexOperand()
   * @generated
   */
  int COMPLEX_OPERAND = 17;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_OPERAND__OPERATOR = OPERAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_OPERAND__EXPRESSION = OPERAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Complex Operand</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_OPERAND_FEATURE_COUNT = OPERAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.MessageImpl <em>Message</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.MessageImpl
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getMessage()
   * @generated
   */
  int MESSAGE = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__MESSAGE = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Recipient</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__RECIPIENT = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Message</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.RuleModel <em>Rule Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Model</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.RuleModel
   * @generated
   */
  EClass getRuleModel();

  /**
   * Returns the meta object for the containment reference list '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.RuleModel#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.RuleModel#getImports()
   * @see #getRuleModel()
   * @generated
   */
  EReference getRuleModel_Imports();

  /**
   * Returns the meta object for the containment reference list '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.RuleModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.RuleModel#getElements()
   * @see #getRuleModel()
   * @generated
   */
  EReference getRuleModel_Elements();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.RuleElement <em>Rule Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Element</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.RuleElement
   * @generated
   */
  EClass getRuleElement();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Rule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Rule#getName()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Name();

  /**
   * Returns the meta object for the reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Rule#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Event</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Rule#getEvent()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Event();

  /**
   * Returns the meta object for the containment reference list '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Rule#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Rule#getActions()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Actions();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Action#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Action#getName()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Name();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Query <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Query
   * @generated
   */
  EClass getQuery();

  /**
   * Returns the meta object for the containment reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Query#getSelect <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Select</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Query#getSelect()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Select();

  /**
   * Returns the meta object for the containment reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Query#getWhere <em>Where</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Where</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Query#getWhere()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Where();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.AddingSelect <em>Adding Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Adding Select</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.AddingSelect
   * @generated
   */
  EClass getAddingSelect();

  /**
   * Returns the meta object for the attribute '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.AddingSelect#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.AddingSelect#getOperation()
   * @see #getAddingSelect()
   * @generated
   */
  EAttribute getAddingSelect_Operation();

  /**
   * Returns the meta object for the reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.AddingSelect#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Element</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.AddingSelect#getElement()
   * @see #getAddingSelect()
   * @generated
   */
  EReference getAddingSelect_Element();

  /**
   * Returns the meta object for the attribute '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.AddingSelect#isAll <em>All</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>All</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.AddingSelect#isAll()
   * @see #getAddingSelect()
   * @generated
   */
  EAttribute getAddingSelect_All();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.SetSelect <em>Set Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Set Select</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.SetSelect
   * @generated
   */
  EClass getSetSelect();

  /**
   * Returns the meta object for the reference list '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.SetSelect#getSelection <em>Selection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Selection</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.SetSelect#getSelection()
   * @see #getSetSelect()
   * @generated
   */
  EReference getSetSelect_Selection();

  /**
   * Returns the meta object for the attribute '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.SetSelect#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.SetSelect#getOperator()
   * @see #getSetSelect()
   * @generated
   */
  EAttribute getSetSelect_Operator();

  /**
   * Returns the meta object for the containment reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.SetSelect#getSelect <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Select</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.SetSelect#getSelect()
   * @see #getSetSelect()
   * @generated
   */
  EReference getSetSelect_Select();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Where <em>Where</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Where</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Where
   * @generated
   */
  EClass getWhere();

  /**
   * Returns the meta object for the reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Where#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Left</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Where#getLeft()
   * @see #getWhere()
   * @generated
   */
  EReference getWhere_Left();

  /**
   * Returns the meta object for the attribute '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Where#getLogicalOperator <em>Logical Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Logical Operator</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Where#getLogicalOperator()
   * @see #getWhere()
   * @generated
   */
  EAttribute getWhere_LogicalOperator();

  /**
   * Returns the meta object for the reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Where#getRightVariable <em>Right Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Right Variable</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Where#getRightVariable()
   * @see #getWhere()
   * @generated
   */
  EReference getWhere_RightVariable();

  /**
   * Returns the meta object for the attribute '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Where#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Where#getRight()
   * @see #getWhere()
   * @generated
   */
  EAttribute getWhere_Right();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Recipient <em>Recipient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recipient</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Recipient
   * @generated
   */
  EClass getRecipient();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.ConcreteRecipient <em>Concrete Recipient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Concrete Recipient</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.ConcreteRecipient
   * @generated
   */
  EClass getConcreteRecipient();

  /**
   * Returns the meta object for the attribute '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.ConcreteRecipient#getUser <em>User</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>User</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.ConcreteRecipient#getUser()
   * @see #getConcreteRecipient()
   * @generated
   */
  EAttribute getConcreteRecipient_User();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.When <em>When</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>When</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.When
   * @generated
   */
  EClass getWhen();

  /**
   * Returns the meta object for the containment reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.When#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.When#getLeft()
   * @see #getWhen()
   * @generated
   */
  EReference getWhen_Left();

  /**
   * Returns the meta object for the attribute '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.When#getLogicalOperator <em>Logical Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Logical Operator</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.When#getLogicalOperator()
   * @see #getWhen()
   * @generated
   */
  EAttribute getWhen_LogicalOperator();

  /**
   * Returns the meta object for the containment reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.When#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.When#getRight()
   * @see #getWhen()
   * @generated
   */
  EReference getWhen_Right();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Expression#getPlainOperand <em>Plain Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Plain Operand</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Expression#getPlainOperand()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_PlainOperand();

  /**
   * Returns the meta object for the containment reference list '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Expression#getComplexOperands <em>Complex Operands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Complex Operands</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Expression#getComplexOperands()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_ComplexOperands();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Operand <em>Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operand</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Operand
   * @generated
   */
  EClass getOperand();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.PlainOperand <em>Plain Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plain Operand</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.PlainOperand
   * @generated
   */
  EClass getPlainOperand();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Numeral <em>Numeral</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Numeral</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Numeral
   * @generated
   */
  EClass getNumeral();

  /**
   * Returns the meta object for the attribute '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Numeral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Numeral#getValue()
   * @see #getNumeral()
   * @generated
   */
  EAttribute getNumeral_Value();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.QueryOperand <em>Query Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query Operand</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.QueryOperand
   * @generated
   */
  EClass getQueryOperand();

  /**
   * Returns the meta object for the reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.QueryOperand#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Query</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.QueryOperand#getQuery()
   * @see #getQueryOperand()
   * @generated
   */
  EReference getQueryOperand_Query();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.ComplexOperand <em>Complex Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Operand</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.ComplexOperand
   * @generated
   */
  EClass getComplexOperand();

  /**
   * Returns the meta object for the attribute '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.ComplexOperand#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.ComplexOperand#getOperator()
   * @see #getComplexOperand()
   * @generated
   */
  EAttribute getComplexOperand_Operator();

  /**
   * Returns the meta object for the containment reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.ComplexOperand#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.ComplexOperand#getExpression()
   * @see #getComplexOperand()
   * @generated
   */
  EReference getComplexOperand_Expression();

  /**
   * Returns the meta object for class '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Message <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Message
   * @generated
   */
  EClass getMessage();

  /**
   * Returns the meta object for the attribute '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Message#getMessage <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Message</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Message#getMessage()
   * @see #getMessage()
   * @generated
   */
  EAttribute getMessage_Message();

  /**
   * Returns the meta object for the containment reference '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.Message#getRecipient <em>Recipient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Recipient</em>'.
   * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.Message#getRecipient()
   * @see #getMessage()
   * @generated
   */
  EReference getMessage_Recipient();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RuleDetectionDslFactory getRuleDetectionDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleModelImpl <em>Rule Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleModelImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getRuleModel()
     * @generated
     */
    EClass RULE_MODEL = eINSTANCE.getRuleModel();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_MODEL__IMPORTS = eINSTANCE.getRuleModel_Imports();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_MODEL__ELEMENTS = eINSTANCE.getRuleModel_Elements();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleElementImpl <em>Rule Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleElementImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getRuleElement()
     * @generated
     */
    EClass RULE_ELEMENT = eINSTANCE.getRuleElement();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__NAME = eINSTANCE.getRule_Name();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__EVENT = eINSTANCE.getRule_Event();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__ACTIONS = eINSTANCE.getRule_Actions();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ActionImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__NAME = eINSTANCE.getAction_Name();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.QueryImpl <em>Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.QueryImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getQuery()
     * @generated
     */
    EClass QUERY = eINSTANCE.getQuery();

    /**
     * The meta object literal for the '<em><b>Select</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__SELECT = eINSTANCE.getQuery_Select();

    /**
     * The meta object literal for the '<em><b>Where</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__WHERE = eINSTANCE.getQuery_Where();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.AddingSelectImpl <em>Adding Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.AddingSelectImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getAddingSelect()
     * @generated
     */
    EClass ADDING_SELECT = eINSTANCE.getAddingSelect();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDING_SELECT__OPERATION = eINSTANCE.getAddingSelect_Operation();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDING_SELECT__ELEMENT = eINSTANCE.getAddingSelect_Element();

    /**
     * The meta object literal for the '<em><b>All</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDING_SELECT__ALL = eINSTANCE.getAddingSelect_All();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.SelectImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.SetSelectImpl <em>Set Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.SetSelectImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getSetSelect()
     * @generated
     */
    EClass SET_SELECT = eINSTANCE.getSetSelect();

    /**
     * The meta object literal for the '<em><b>Selection</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SET_SELECT__SELECTION = eINSTANCE.getSetSelect_Selection();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SET_SELECT__OPERATOR = eINSTANCE.getSetSelect_Operator();

    /**
     * The meta object literal for the '<em><b>Select</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SET_SELECT__SELECT = eINSTANCE.getSetSelect_Select();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.WhereImpl <em>Where</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.WhereImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getWhere()
     * @generated
     */
    EClass WHERE = eINSTANCE.getWhere();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHERE__LEFT = eINSTANCE.getWhere_Left();

    /**
     * The meta object literal for the '<em><b>Logical Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE__LOGICAL_OPERATOR = eINSTANCE.getWhere_LogicalOperator();

    /**
     * The meta object literal for the '<em><b>Right Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHERE__RIGHT_VARIABLE = eINSTANCE.getWhere_RightVariable();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE__RIGHT = eINSTANCE.getWhere_Right();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RecipientImpl <em>Recipient</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RecipientImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getRecipient()
     * @generated
     */
    EClass RECIPIENT = eINSTANCE.getRecipient();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ConcreteRecipientImpl <em>Concrete Recipient</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ConcreteRecipientImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getConcreteRecipient()
     * @generated
     */
    EClass CONCRETE_RECIPIENT = eINSTANCE.getConcreteRecipient();

    /**
     * The meta object literal for the '<em><b>User</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONCRETE_RECIPIENT__USER = eINSTANCE.getConcreteRecipient_User();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.WhenImpl <em>When</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.WhenImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getWhen()
     * @generated
     */
    EClass WHEN = eINSTANCE.getWhen();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHEN__LEFT = eINSTANCE.getWhen_Left();

    /**
     * The meta object literal for the '<em><b>Logical Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHEN__LOGICAL_OPERATOR = eINSTANCE.getWhen_LogicalOperator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHEN__RIGHT = eINSTANCE.getWhen_Right();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ExpressionImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Plain Operand</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__PLAIN_OPERAND = eINSTANCE.getExpression_PlainOperand();

    /**
     * The meta object literal for the '<em><b>Complex Operands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__COMPLEX_OPERANDS = eINSTANCE.getExpression_ComplexOperands();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.OperandImpl <em>Operand</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.OperandImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getOperand()
     * @generated
     */
    EClass OPERAND = eINSTANCE.getOperand();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.PlainOperandImpl <em>Plain Operand</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.PlainOperandImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getPlainOperand()
     * @generated
     */
    EClass PLAIN_OPERAND = eINSTANCE.getPlainOperand();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.NumeralImpl <em>Numeral</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.NumeralImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getNumeral()
     * @generated
     */
    EClass NUMERAL = eINSTANCE.getNumeral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMERAL__VALUE = eINSTANCE.getNumeral_Value();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.QueryOperandImpl <em>Query Operand</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.QueryOperandImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getQueryOperand()
     * @generated
     */
    EClass QUERY_OPERAND = eINSTANCE.getQueryOperand();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY_OPERAND__QUERY = eINSTANCE.getQueryOperand_Query();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ComplexOperandImpl <em>Complex Operand</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.ComplexOperandImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getComplexOperand()
     * @generated
     */
    EClass COMPLEX_OPERAND = eINSTANCE.getComplexOperand();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPLEX_OPERAND__OPERATOR = eINSTANCE.getComplexOperand_Operator();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_OPERAND__EXPRESSION = eINSTANCE.getComplexOperand_Expression();

    /**
     * The meta object literal for the '{@link eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.MessageImpl <em>Message</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.MessageImpl
     * @see eagledata.core.dsl.ruledetection.ruleDetectionDsl.impl.RuleDetectionDslPackageImpl#getMessage()
     * @generated
     */
    EClass MESSAGE = eINSTANCE.getMessage();

    /**
     * The meta object literal for the '<em><b>Message</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE__MESSAGE = eINSTANCE.getMessage_Message();

    /**
     * The meta object literal for the '<em><b>Recipient</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE__RECIPIENT = eINSTANCE.getMessage_Recipient();

  }

} //RuleDetectionDslPackage
