/**
 * generated by Xtext 2.9.2
 */
package eagledata.core.dsl.datadesc.dataDsl.impl;

import eagledata.core.dsl.datadesc.dataDsl.BasicType;
import eagledata.core.dsl.datadesc.dataDsl.DataDslPackage;
import eagledata.core.dsl.datadesc.dataDsl.DataTypeRefinement;
import eagledata.core.dsl.datadesc.dataDsl.Option;
import eagledata.core.dsl.datadesc.dataDsl.SubstringConcept;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Type Refinement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link eagledata.core.dsl.datadesc.dataDsl.impl.DataTypeRefinementImpl#getRefine <em>Refine</em>}</li>
 *   <li>{@link eagledata.core.dsl.datadesc.dataDsl.impl.DataTypeRefinementImpl#getSubsequences <em>Subsequences</em>}</li>
 *   <li>{@link eagledata.core.dsl.datadesc.dataDsl.impl.DataTypeRefinementImpl#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DataTypeRefinementImpl extends TypeSpecificationImpl implements DataTypeRefinement
{
  /**
   * The default value of the '{@link #getRefine() <em>Refine</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefine()
   * @generated
   * @ordered
   */
  protected static final BasicType REFINE_EDEFAULT = BasicType.STRING;

  /**
   * The cached value of the '{@link #getRefine() <em>Refine</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefine()
   * @generated
   * @ordered
   */
  protected BasicType refine = REFINE_EDEFAULT;

  /**
   * The cached value of the '{@link #getSubsequences() <em>Subsequences</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubsequences()
   * @generated
   * @ordered
   */
  protected EList<SubstringConcept> subsequences;

  /**
   * The cached value of the '{@link #getOptions() <em>Options</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOptions()
   * @generated
   * @ordered
   */
  protected EList<Option> options;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataTypeRefinementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DataDslPackage.Literals.DATA_TYPE_REFINEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BasicType getRefine()
  {
    return refine;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRefine(BasicType newRefine)
  {
    BasicType oldRefine = refine;
    refine = newRefine == null ? REFINE_EDEFAULT : newRefine;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DataDslPackage.DATA_TYPE_REFINEMENT__REFINE, oldRefine, refine));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<SubstringConcept> getSubsequences()
  {
    if (subsequences == null)
    {
      subsequences = new EObjectContainmentEList<SubstringConcept>(SubstringConcept.class, this, DataDslPackage.DATA_TYPE_REFINEMENT__SUBSEQUENCES);
    }
    return subsequences;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Option> getOptions()
  {
    if (options == null)
    {
      options = new EObjectContainmentEList<Option>(Option.class, this, DataDslPackage.DATA_TYPE_REFINEMENT__OPTIONS);
    }
    return options;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DataDslPackage.DATA_TYPE_REFINEMENT__SUBSEQUENCES:
        return ((InternalEList<?>)getSubsequences()).basicRemove(otherEnd, msgs);
      case DataDslPackage.DATA_TYPE_REFINEMENT__OPTIONS:
        return ((InternalEList<?>)getOptions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DataDslPackage.DATA_TYPE_REFINEMENT__REFINE:
        return getRefine();
      case DataDslPackage.DATA_TYPE_REFINEMENT__SUBSEQUENCES:
        return getSubsequences();
      case DataDslPackage.DATA_TYPE_REFINEMENT__OPTIONS:
        return getOptions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DataDslPackage.DATA_TYPE_REFINEMENT__REFINE:
        setRefine((BasicType)newValue);
        return;
      case DataDslPackage.DATA_TYPE_REFINEMENT__SUBSEQUENCES:
        getSubsequences().clear();
        getSubsequences().addAll((Collection<? extends SubstringConcept>)newValue);
        return;
      case DataDslPackage.DATA_TYPE_REFINEMENT__OPTIONS:
        getOptions().clear();
        getOptions().addAll((Collection<? extends Option>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DataDslPackage.DATA_TYPE_REFINEMENT__REFINE:
        setRefine(REFINE_EDEFAULT);
        return;
      case DataDslPackage.DATA_TYPE_REFINEMENT__SUBSEQUENCES:
        getSubsequences().clear();
        return;
      case DataDslPackage.DATA_TYPE_REFINEMENT__OPTIONS:
        getOptions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DataDslPackage.DATA_TYPE_REFINEMENT__REFINE:
        return refine != REFINE_EDEFAULT;
      case DataDslPackage.DATA_TYPE_REFINEMENT__SUBSEQUENCES:
        return subsequences != null && !subsequences.isEmpty();
      case DataDslPackage.DATA_TYPE_REFINEMENT__OPTIONS:
        return options != null && !options.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (refine: ");
    result.append(refine);
    result.append(')');
    return result.toString();
  }

} //DataTypeRefinementImpl
