/**
 * generated by Xtext 2.9.1
 */
package eagledata.core.dsl.datadesc.ui.contentassist;

import eagledata.core.dsl.datadesc.ui.contentassist.AbstractDataDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DataDslProposalProvider extends AbstractDataDslProposalProvider {
}
