/*
 * generated by Xtext 2.9.1
 */
package eagledata.core.dsl.datadsl.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class DataDslProposalProvider extends AbstractDataDslProposalProvider {
}
