/**
 * generated by Xtext 2.9.2
 */
package uam.eagledata.dsl.semanticnodes.ui.contentassist;

import uam.eagledata.dsl.semanticnodes.ui.contentassist.AbstractSemanticNodesDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SemanticNodesDslProposalProvider extends AbstractSemanticNodesDslProposalProvider {
}
