<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="geoposition" nsURI="http://www.eclipse.org/emf/eagledata/core/model/geoposition"
    nsPrefix="eagledata.core.model.geoposition"/>
