/**
 * generated by Xtext 2.9.2
 */
package uam.eagledata.dsl.query.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uam.eagledata.dsl.query.ui.AbstractQueryDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class QueryDslUiModule extends AbstractQueryDslUiModule {
  public QueryDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
