/**
 * generated by Xtext 2.9.2
 */
package eagledata.core.dsl.rule.ruleDsl;

import eagledata.core.dsl.datadesc.dataDsl.PrimitiveNode;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select Message String</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eagledata.core.dsl.rule.ruleDsl.SelectMessageString#getResponse <em>Response</em>}</li>
 * </ul>
 *
 * @see eagledata.core.dsl.rule.ruleDsl.RuleDslPackage#getSelectMessageString()
 * @model
 * @generated
 */
public interface SelectMessageString extends MessageString
{
  /**
   * Returns the value of the '<em><b>Response</b></em>' reference list.
   * The list contents are of type {@link eagledata.core.dsl.datadesc.dataDsl.PrimitiveNode}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Response</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Response</em>' reference list.
   * @see eagledata.core.dsl.rule.ruleDsl.RuleDslPackage#getSelectMessageString_Response()
   * @model
   * @generated
   */
  EList<PrimitiveNode> getResponse();

} // SelectMessageString
